version: '3'
services:
  c_mongo:
    image: mongo:latest
    volumes:
      - ./minicursos/data:/data/db
  node_server:
    image: rafapg/dio_node_server:latest
    ports:
      - 80:3000
    depends_on:
      - c_mongo
